Part3/accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

Part3/chat/urls.py
from django.urls import path
from chat.views import *

app_name = 'chat'

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('chat_room/', ChatRoom.as_view(), name="chat_room"),
    path("search/", SearchUser.as_view(), name="search_user"),
    path("addfriend/<str:username>", addFriend, name="addfriend"), 
    path("chat/<str:username>", get_message, name="get_message"), 
    path('api/messages', UpdateMessage.as_view()),
    path('api/messages/<int:sender>/<int:receiver>', UpdateMessage.as_view()),
]

Part3/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("chat.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Part3/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


class CustomUser(AbstractUser, UserManager):

    email = models.EmailField(verbose_name="メールアドレス", unique=True, blank=False, null=False)  #emailを必須＆ユニークに設定
    thumbnail = models.ImageField(upload_to="images/thumbnail/", verbose_name="サムネイル", blank=True, null=True)
    USERNAME_FIELD = 'email'   #ログオンIDをユーザ名→Emailへ変更
    REQUIRED_FIELDS = ['username']       #ユーザーを作成するために必要なキーを指定

    def __str__(self):
        return self.email

Part3/chat/models.py
from django.db import models
from accounts.models import CustomUser


class Friends(models.Model):

    class Meta:
        verbose_name = '友達リスト'
        verbose_name_plural = '友達リスト'

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name = "user_friends")
    friend = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="友達", related_name = "friend_friends")

    def __str__(self):
        return f"{self.friend}"
    


class Messages(models.Model):
    
    description = models.TextField()
    sender_name = models.ForeignKey(CustomUser, verbose_name="送信者", on_delete=models.CASCADE, related_name='sender')
    receiver_name = models.ForeignKey(CustomUser, verbose_name="受信者", on_delete=models.CASCADE, related_name='receiver')
    time = models.TimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"To: {self.receiver_name} From: {self.sender_name}"
    
    class Meta:
        ordering = ('timestamp',)
        verbose_name = 'メッセージリスト'
        verbose_name_plural = 'メッセージリスト'
        


Part3/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')

    email = forms.EmailField()


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

    email = forms.EmailField()

Part3/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm
from django.contrib.auth import login


class SignUp(generic.CreateView):

    form_class = CustomUserCreationForm
    success_url = reverse_lazy('chat:chat_room')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        """
        ユーザ登録直後に自動的にログオンさせる。
        self.objectにsave()されたユーザオブジェクトが格納されている。
        """
        valid = super().form_valid(form)
        login(self.request, self.object)   #login処理
        return valid

Part3/chat/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from accounts.models import CustomUser
from django.views import View
from chat.models import Messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from chat.serializers import MessageSerializer



class Home(TemplateView):
    #Home画面を表示するビュー
    template_name = 'home.html'
    
    
class ChatRoom(TemplateView):
    #Home画面を表示するビュー
    template_name = 'chat/chat_box.html'
    

def getFriendsList(username):
    """
    指定したユーザの友達リストを取得
    :param: ユーザ名
    :return: ユーザ名の友達リスト
    """
    try:
        user = CustomUser.objects.get(username=username)
        friends = list(user.user_friends.all())
        return friends
    except:
        return []



class SearchUser(View):
    
    def get(self, request, *args, **kwargs):
        
        if 'search' in self.request.GET:
            query = request.GET.get("search")
            users = list(CustomUser.objects.all())
            user_list = []
            for user in users:
                #検索文字列を含むユーザ情報を取得(自分は除外)
                if query in user.username and user.username != request.user.username:
                    user_list.append(user)
        else:
            user_list = list(CustomUser.objects.all())  #全ユーザ一覧を取得
            for user in user_list:
                if user.username == request.user.username:
                    user_list.remove(user)  #自分のユーザだけ除外
                    break
        
        friends = getFriendsList(request.user.username)  #自分のフレンド一覧を取得
        return render(request, "chat/search.html", {'users': user_list, 'friends': friends})



def addFriend(request, username):
    """
    引数で受け取ったユーザ名(username)を Friendsテーブルに友達として登録する。
    """
    login_user = request.user.username
    friend = CustomUser.objects.get(username=username)
    current_user = CustomUser.objects.get(username=login_user)
    friend_lists = current_user.user_friends.all()
    #既に友達登録済みの場合flag=1にセット
    flag = 0
    for friend_list in friend_lists:
        if friend_list.friend.pk == friend.pk:
            flag = 1
            break
    #フレンド未登録の場合
    if flag == 0:
        #お互いにフレンド登録を行う。
        current_user.user_friends.create(friend=friend)  #ログオンユーザ視点でフレンドを登録
        friend.user_friends.create(friend=current_user)   #フレンド視点でログオンユーザをフレンドに登録
    return redirect("chat:search_user")



def get_message(request, username):
    """
    特定ユーザ間のチャット情報を取得する
    """
    friend = CustomUser.objects.get(username=username)
    current_user = CustomUser.objects.get(username=request.user.username)
    messages = Messages.objects.filter(sender_name=current_user.id, receiver_name=friend.id) | \
               Messages.objects.filter(sender_name=friend.id, receiver_name=current_user.id)
    friends = getFriendsList(request.user.username)
    return render(request, "chat/messages.html",
                      {'messages': messages,
                       'friends': friends,
                       'current_user': current_user, 'friend': friend})
    
   
    
class UpdateMessage(View):
    
    def post(self, request, *args, **kwargs):
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        
        return JsonResponse(serializer.errors, status=400)
    
    
    def get(self, request, *args, **kwargs):
        sender = self.kwargs.get('sender')
        receiver =  self.kwargs.get('receiver')
        messages = Messages.objects.filter(sender_name=sender, receiver_name=receiver, seen=False)
        for message in messages:
            message.seen = True
            message.save()
        serializer = MessageSerializer(instance=messages, many=True)
        return JsonResponse(serializer.data, safe=False)


Part3/templates/chat/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Django Chat</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/chat_room.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body>
<html>
<head>
<nav class="navbar navbar-expand-md navbar-dark bg-info navbar-fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav">
       <li class="nav-item">
        <a class="nav-link" href="#">{{ user.username}}さん</a></li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'chat:search_user' %}">検索</a>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">ログアウト</a></li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'password_change' %}">パスワード変更</a>
      </li>
      </ul>
    </div>
  </nav>
</head>
<body>
<div class="container">
{% block title%}{% endblock %}
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h5>ユーザ検索画面</h5>
            </div>
          </div>
          <div class="inbox_chat">
            {% for friend in friends %}
            <a href="{% url 'chat:get_message' friend.friend.username %}">
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="{{ friend.friend.thumbnail.url }}" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>{{friend.friend.username}}</h5>
                </div>
              </div>
            </div>
            </a>
            {% endfor %}
            </div>
        </div>
        {% block contents%}{% endblock %}
      </div>
      <p class="text-center top_spac"> It is composed of Django + DRF + JavaScript.<a target="_blank" href="https://www.linkedin.com/in/sunil-rajput-nattho-singh/"></a></p>
    </div></div>
    </body>
    </html>
<script type="text/javascript"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<!-- Ajax Post送信のCSRF対策-->    
<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });   
</script>

</body>
</html>

Part3/templates/chat/chat_box.html
{% extends './base.html' %}
{% load static %}
{% block title %}
<h3 class=" text-center">Django-Chat画面</h3>
{% endblock %}
{% block contents %}
<div class="mesgs">
    <div class="msg_history">
      <div class="incoming_msg">
        <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        <div class="received_msg">
          <div class="received_withd_msg">
            <p>何かお困りでしょうか？</p>
            <span class="time_date"> 11:01 AM    |    June 9</span></div>
        </div>
      </div>
      <div class="outgoing_msg">
        <div class="sent_msg">
          <p>Djangoの学習に躓いています。助けてください。</p>
          <span class="time_date"> 11:01 AM    |    June 9</span> </div>
      </div>
      <div class="incoming_msg">
        <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        <div class="received_msg">
          <div class="received_withd_msg">
            <p>了解しました。</p>
            <span class="time_date"> 11:01 AM    |    Yesterday</span></div>
        </div>
      </div>
    </div>
    <div class="type_msg">
      <div class="input_msg_write">
        <input type="text" class="write_msg" placeholder="メッセージを入力してください。" />
        <button class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
      </div>
    </div>
  </div>
{% endblock %}

Part3/templates/chat/messages.html
{% extends './base.html' %}
{% load static %}
{% block title %}
<h3 class=" text-center">Django-Chat画面</h3>
{% endblock %}
{% block contents %}
<div class="mesgs">
    <div class="msg_history" id="board">
        {% for message in messages %}
        {% if friend == message.sender_name %}
        <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="{{ friend.thumbnail.url }}" alt="sunil"> </div>
            <div class="received_msg">
                <div class="received_withd_msg">
                    <p>{{message.description}}</p>
                    <span class="time_date">{{message.time}}</span>
                </div>
            </div>
        </div>
        {% else %}
        <div class="outgoing_msg">
            <div class="sent_msg">
                <p>{{message.description}}</p>
                <span class="time_date">{{message.time}}</span>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="type_msg">
        <form method="post" class="form-group" id="chat-box">
            {% csrf_token %}
            <div class="input_msg_write">
                <input type="text" class="write_msg" placeholder="メッセージを送信..." name="message" id="msg_field">
                <button type="submit" name="send" class="msg_send_btn"><i class="fa fa-paper-plane-o"
                        aria-hidden="true"></i></button>
            </div>
        </form>
    </div>
</div>

<script>
    //メッセージの送信者（会話相手）と受信者（自分自身）を取得しておく
    sender_id = "{{ friend.id }}";
    receiver_id = "{{ current_user.id }}";
    //スクロールバーを自動で下まで移動する処理を定義
    let messageBody = document.querySelector('.msg_history');
    messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
    function scrolltoend() {
        $('#board').stop().animate({
            scrollTop: $('#board')[0].scrollHeight
        }, 800);
    }
    //画面上に追加するメッセージの定義
    const text_box = '<div class="outgoing_msg">' +
        '<div class="sent_msg">' +
        '<p>{description}</p>' +
        '<span class="time_date">{time}</span>' +
        '</div>' +
        '</div>'
    //送信ボタンクリック時の処理を定義
    $(function () {
        $('#chat-box').on('submit', function (event) {
            event.preventDefault();  //ページノリロードを防止
            let message = $('#msg_field');
            //sendメソッドを実行
            send('{{ current_user.id }}', '{{ friend.id }}', message.val());
            message.val(''); //メッセージ入力欄をリセット
        })
    })
    function send(sender, receiver, message){
        //メッセージ送信
        $.post('/api/messages', '{"sender_name": "' + sender + '", "receiver_name": "' +
                receiver + '","description": "' + message + '" }', function (data) {
            let field = text_box.replace('{description}', message);
            let today = new Date();
            let time = today.getHours() + ":" + today.getMinutes();
            field = field.replace('{time}', time);
            $('#board').append(field);
            scrolltoend();  //スクロールバーを下まで移動
        })
    }

    //receive関数の定期実行
    $(function () {
        setInterval(receive, 1000, '{{friend.thumbnail.url}}')
    })
 
    //receive関数の定期実行
    $(function () {
        setInterval(receive, 1000, '{{friend.thumbnail.url}}')
    })


    const text = '<div class="incoming_ms">' +
        '<div class="incoming_msg_img"> <img src="{thumbnail}" alt="sunil"> </div>' +
        '<div class="received_msg">' +
        '<div class="received_withd_msg">' +
        '<p>{description}</p>' +
        '<span class="time_date">{time}</span>' +
        '</div>' +
        '</div>' +
        '</div>'
        
    function receive(thumbnail){
        $.get('/api/messages/' + sender_id + '/' + receiver_id, function(data){
            if(data.length !== 0){
                for(var i = 0; i < data.length; i++){
                    var field = text.replace('{description}', data[i].description);
                    var time = data[i].time.slice(0, 5)
                    field = field.replace('{time}', time);
                    field = field.replace('{thumbnail}', thumbnail);
                    $('#board').append(field);
                    scrolltoend();
                }
            }
        })
    }
</script>


{% endblock %}

Part3/templates/chat/search.html
{% extends './base.html' %}
{% load static %}
{% block title %}
<h3 class=" text-center">Django-Chat検索画面</h3>
{% endblock %}
{% block contents %}
<div class="mesgs">
    <div class="msg_history">
        <div class="wrapper" style="width: 400px;">
            <h4 style="margin: 16px 0px">ユーザを追加する</h4>
            <div class="topnav">
                <div class="search-container">
                    <form method="get">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control-sm" placeholder="ユーザ名で検索" name="search"
                                saria-describedby="basic-addon2">
                            <button type="submit" class="btn btn-success ml-2">検索</button>
                        </div>
                    </form>
                </div>
            </div>
            <ul class="list-group list-group-flush mt-3">
                {% for user in users %}
                <a href="{% url 'chat:addfriend' user.username %}" id="user_card">
                    <li class="list-group-item list-group-item-action">
                        <div class="row">
                            <div class="col">
                                <img src="{{ user.thumbnail.url }}" style="width: 50px; height: 50px;">
                            </div>
                            <div class="col">
                                <div class="row user-add">
                                    <p>@{{user.username}}</p>
                                </div>
                            </div>
                        </div>
                    </li>
                </a>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

Part3/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
   <style>
        body{
            background-image: url("{% static 'images/top.png' %}");
            background-position: center;
            background-size: cover;
            height: 750px;
            background-repeat: no-repeat
        }

        .navbar{
            background-color: #5053fc;
            overflow: hidden;
            float: left;
            width: 100%;
            text-align: center;
            text-decoration: none;
            font-size: 18px;
            padding: 8px 8px;
            color: white
        }

        .navbar a:hover{
            text-decoration: none;
        }

        .navbar-right a{
            margin-left: 16px;
        }


    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Djangoチャットアプリ</title>
</head>
<body>

    <div class="navbar">
        <a href="/" class="text-white">Djangoチャットアプリ</a>
        <div class="navbar-right">
            <a href="{% url 'login' %}" class="login_text text-white">ログイン</a>
            <a href="{% url 'signup' %}" class="register text text-white">ユーザ登録</a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>
</html>